name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  validate:
    name: Validate Shell Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate syntax of status-check.sh
        run: bash -n status-check.sh

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simulate test execution
        run: |
          echo "Running tests"
          exit 0

  package:
    name: Package Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dummy report
        run: |
          mkdir -p report
          echo "Relatório de execução - $(date)" > report/status.txt
          zip -r report.zip report/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
