name: CI

on:
  push:
    branches: [main, workflow]
  pull_request:
    branches: [main, workflow]
  workflow_dispatch:

jobs:

  validate:
    name: Validate Shell Script
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.validate-step.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: validate-step
        name: Verify Syntax
        run: |
          if bash -n scripts/status-check.sh; then
            echo "status=Sintaxe válida" >> $GITHUB_OUTPUT
          else
            echo "status=Sintaxe inválida" >> $GITHUB_OUTPUT
          fi
  

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      result: ${{ steps.test-step.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: test-step
        name: Run test simulation and save log
        run: |
          set -e
          echo "Running tests"
          echo "status=Comando de teste executado com sucesso" >> $GITHUB_OUTPUT
          exit 0

  package:
    name: Package Report
    runs-on: ubuntu-latest
    needs: [validate, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Concatenate logs and zip
        run: |
          mkdir -p report
          echo "# Relatório de Execução – $(date)" > report/status.txt
          echo "" >> report/status.txt
          echo -e "\n--- [VALIDATE] ---" >> report/status.txt
          echo "${{ needs.validate.outputs.result }}" >> report/status.txt
          echo "" >> report/status.txt
          echo -e "\n--- [TEST] ---" >> report/status.txt
          echo "${{ needs.test.outputs.result }}" >> report/status.txt
          zip -r report.zip report/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
