name: CI

on:
  push:
    branches: [workflow]
  pull_request:
    branches: [workflow]
  workflow_dispatch:

jobs:

  validate:
    name: Validate Shell Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate script syntax and save log
        run: |
          mkdir -p logs
          bash -n scripts/status-check.sh > logs/validate.log 2>&1 \
          && echo "Sintaxe válida" >> logs/validate.log \
          || echo "Sintaxe inválida" >> logs/validate.log

      - name: Upload validate log
        uses: actions/upload-artifact@v4
        with:
          name: validate-log
          path: logs/validate.log

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test simulation and save log
        run: |
          mkdir -p logs
          echo "Executando testes" > logs/test.log
          echo "✓ Teste 1: OK" >> logs/test.log
          echo "✓ Teste 2: OK" >> logs/test.log
          exit 0

      - name: Upload test log
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: logs/test.log

  package:
    name: Package Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download validate log
        uses: actions/download-artifact@v4
        with:
          name: validate-log
          path: logs

      - name: Download test log
        uses: actions/download-artifact@v4
        with:
          name: test-log
          path: logs

      - name: Concatenate logs and zip
        run: |
          mkdir -p report
          echo "# Relatório de Execução – $(date)" > report/status.txt
          echo -e "\n--- [VALIDATE] ---" >> report/status.txt
          cat logs/validate.log >> report/status.txt
          echo -e "\n--- [TEST] ---" >> report/status.txt
          cat logs/test.log >> report/status.txt
          zip -r report.zip report/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
