name: Deploy Automático

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Simular Deploy para Produção
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Exibir domínio de produção
        run: echo "Deploying to $PROD_DOMAIN"
